export default [
	"In the past month, have you had boba (bubble tea) more than once?",
	"In the past month, have you listened to any of these artists: Khai Dreams, Joji, Kesha, ThxSoMch?",
	"Do you like kpop?",
	"Do you like Ghibli movies?",
	"Do you own, or would you own a cat?",
	"Do you have one or more plushies?",
	"Do you play valorant or league?",
	"If you do, are you silver/gold?",
	"Do you mostly play MMO games? (Massive Multiplayer Online games)",
	"Do you mostly play multiplayer games over singleplayer games?",
	"Is one of your favourite singleplayer games Stardew Valley?",
	"In the past year, have you dyed your hair, or a portion of your hair?",
	"Do you usually wear oversized clothes or sweaters?",
	"Do you usually carry around a small backpack or a tote bag?",
	"Do you mostly use Japanese stationary (pens, pencils, notebooks, etc)?",
	"Do you enjoy the cottagecore aesthetic?",
	"Do you have a flower tattoo?",
	"Does your dad work in a STEM related field?",
	"Do you consider art to be a core hobby?",
	"In the past month, have you used this emoticon: ;-;?",
];
